apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp-f7c7l
  name: winmach
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-f7c7l
      machine.openshift.io/cluster-api-machineset: winmach
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-f7c7l
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: winmach
        machine.openshift.io/os-id: Windows
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 128
          kind: VSphereMachineProviderSpec
          memoryMiB: 16384
          network:
            devices:
            - networkName: VM Network
          numCPUs: 4
          numCoresPerSocket: 1
          snapshot: ""
          template: /Datacenter/vm/openshift4-9r24l/openshift4-9r24l-windows
          userDataSecret:
            name: windows-user-data
          workspace:
             datacenter: Datacenter
             datastore: datastore1
             folder: /Datacenter/vm/openshift4-9r24l
             resourcePool: /Datacenter/host/homecluster/Resources
             server: vsphere.example.com
